### ISSUE TITLE
Latest update gives error in console 

### ISSUE THREAD

**Issue by kgbcupcake** [Spacetornado/EatLess#1]
Jotunn.Entities.CustomItem.ToString () (at <248abca63c11469bad2fac12eb8ab7b7>:0)
System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.String.Format (System.String format, System.Object arg0) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Jotunn.Entities.CustomItem.IsValid () (at <248abca63c11469bad2fac12eb8ab7b7>:0)
Jotunn.Managers.ItemManager.AddItem (Jotunn.Entities.CustomItem customItem) (at <248abca63c11469bad2fac12eb8ab7b7>:0)
EatLess.EatLess.AddFoodsAndRecipes () (at <87f052be1ec4456abe0848eb6965eb0b>:0)
EatLess.EatLess.Awake () (at <87f052be1ec4456abe0848eb6965eb0b>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

**Comment by Spacetornado** [comment]
Issue is fixed now in the latest version 0.6.0 of the mod. The custom Wolf Skewer food/recipe was not loading properly and causing the error. Thanks for reporting.
