### ISSUE TITLE
Everything still works fine 

### ISSUE THREAD

**Issue by kgbcupcake** [Spacetornado/EatLess#2]
[Info   :   BepInEx] Loading [EatLess 0.0.1]
[Warning: Unity Log] Failed to find expected binary shader data in 'Custom/Creature'.
[Warning: Unity Log] Failed to find expected binary shader data in 'Custom/Creature'.
[Warning: Unity Log] Failed to find expected binary shader data in 'Custom/Creature'.

Doesn't break anything, just figured I would let you know

**Comment by Spacetornado** [comment]
Thanks. Not sure what it's complaining about so I'll just leave it alone.
