### ISSUE TITLE
HighCal Sausage/Muckshake misslabeled

### ISSUE THREAD

**Issue by Alistair-Macbain** [Spacetornado/EatLess#6]
The High Cal Sausage and Muckshake variants are labeled wrong. The normal versions unlock with Cauldron lvl 2. The HighCal ones unlock with Cauldron lvl 1.

**Comment by Spacetornado** [comment]
All the high-cal recipes only require the level 1 cauldron, so this is by design.

I might add the cauldron requirements at some point, but I don't really care about them as I've unlocked lvl 5 cauldron.
